export const questions = [
  { question: "What are the benefits of a balanced diet?", category: "Health", color: "#FFB6C1", icon: "/health_icon.png" },
  { question: "How does the internet work?", category: "Technology", color: "#87CEEB", icon: "/technology_icon.png" },
  { question: "What is the significance of the scientific method?", category: "Education", color: "#FFD700", icon: "/education_icon.png" },
  { question: "What are the main causes of climate change?", category: "Environment", color: "#98FB98", icon: "/environment_icon.png" },
  { question: "How can we improve mental health awareness?", category: "Health", color: "#FFB6C1", icon: "/health_icon.png" },
  { question: "What are the different types of renewable energy?", category: "Technology", color: "#87CEEB", icon: "/technology_icon.png" },
  { question: "What is the role of a teacher in student development?", category: "Education", color: "#FFD700", icon: "/education_icon.png" },
  { question: "How does cryptocurrency work?", category: "Finance", color: "#D2B48C", icon: "/finance_icon.png" },
  { question: "What are the impacts of social media on society?", category: "Social", color: "#FF69B4", icon: "/social_icon.png" },
  { question: "What are effective study techniques for students?", category: "Education", color: "#FFD700", icon: "/education_icon.png" },
  { question: "What are the main principles of design thinking?", category: "Business", color: "#FFA07A", icon: "/business_icon.png" },
  { question: "How can individuals reduce their carbon footprint?", category: "Environment", color: "#98FB98", icon: "/environment_icon.png" },
  { question: "What is the importance of coding in today's world?", category: "Technology", color: "#87CEEB", icon: "/technology_icon.png" },
  { question: "How do vaccines work to protect against diseases?", category: "Health", color: "#FFB6C1", icon: "/health_icon.png" },
  { question: "What are the benefits of reading regularly?", category: "Education", color: "#FFD700", icon: "/education_icon.png" },
  { question: "What is artificial intelligence and its applications?", category: "Technology", color: "#87CEEB", icon: "/technology_icon.png" },
  { question: "How can we promote gender equality in the workplace?", category: "Social", color: "#FF69B4", icon: "/social_icon.png" },
  { question: "What are common signs of stress and how can we manage it?", category: "Health", color: "#FFB6C1", icon: "/health_icon.png" },
  { question: "What is the impact of automation on jobs?", category: "Economy", color: "#FF6347", icon: "/finance_icon.png" },
  { question: "What are some effective time management strategies?", category: "Personal Development", color: "#20B2AA", icon: "/education_icon.png" },
  { question: "How does climate change affect biodiversity?", category: "Environment", color: "#98FB98", icon: "/environment_icon.png" },
  { question: "What are the ethical considerations of genetic engineering?", category: "Science", color: "#9370DB", icon: "/science_icon.png" },
  { question: "How can technology enhance education?", category: "Education", color: "#FFD700", icon: "/education_icon.png" },
  { question: "What are the principles of effective communication?", category: "Business", color: "#FFA07A", icon: "/business_icon.png" },
  { question: "What is mindfulness and how can it benefit mental health?", category: "Health", color: "#FFB6C1", icon: "/health_icon.png" },
  { question: "What are the challenges of online learning?", category: "Education", color: "#FFD700", icon: "/education_icon.png" },
  { question: "How can we promote sustainable living?", category: "Environment", color: "#98FB98", icon: "/environment_icon.png" },
  { question: "What are the key elements of a successful business plan?", category: "Business", color: "#FFA07A", icon: "/business_icon.png" },
  { question: "How does nutrition impact physical performance?", category: "Health", color: "#FFB6C1", icon: "/health_icon.png" },
  { question: "What are the benefits of learning a second language?", category: "Education", color: "#FFD700", icon: "/education_icon.png" },
  { question: "What is the role of cybersecurity in protecting information?", category: "Technology", color: "#87CEEB", icon: "/technology_icon.png" },
  { question: "What are the benefits of volunteering in the community?", category: "Social", color: "#FF69B4", icon: "/social_icon.png" }
];